create table logs (id int8 generated by default as identity,
                    content_type varchar(255),
                    creation_time timestamp,
                    method varchar(255),
                    remote_user varchar(255),
                    response_status_code int4,
                    uri varchar(255),
                    primary key (id)
);

create table news (id int8 generated by default as identity,
                    description varchar(255),
                    image varchar(255),
                    title varchar(255),
                    username varchar(255),
                    user_id uuid,
                    primary key (id)
);

create table tags (id int8 generated by default as identity,
                    tag varchar(255),
                    news_id int8,
                    primary key (id)
);

create table user_entity (id uuid not null,
                            avatar varchar(255),
                            email varchar(255),
                            name varchar(255),
                            password varchar(255),
                            role varchar(255),
                            primary key (id)
);

alter table if exists user_entity
            add constraint user_email
            unique (email);

alter table if exists news
            add constraint user_id_fk
            foreign key (user_id) references user_entity;

alter table if exists tags
            add constraint news_id_fk
            foreign key (news_id) references news;